# Generated by fusen: do not edit by hand

expect_render <- function(template, FUN){

  render_dir <- tempfile()

  dir.create(render_dir)
  dir.create(file.path(render_dir, "www"))

  file.copy(
    system.file("rmarkdown", template, package = "finddxtemplate"),
    render_dir
  )

  file <- file.path(render_dir, template)

  expect_output(
    expect_message(
      rmarkdown::render(
        input = file,
        output_format = FUN,
        output_dir = render_dir),
      "Output created"
    ),
    "pandoc"
  )
}

test_that("html_document_finddx works", {
  expect_render(
    template = "template.Rmd", 
    FUN = html_document_finddx()
  )
})
