# Generated by fusen: do not edit by hand

#' Convert a .Rmd file into a .html file according to finddx design / template.
#'
#' @importFrom rmarkdown html_document
#'
#' @param toc Boolean. To include a table of contents in the output. Default is TRUE.
#' @param toc_depth Numeric. Depth of headers to include in table of contents. Default is 4.
#' @param toc_float Boolean. To float the table of contents to the left of the document. Default is TRUE.
#' @param code_folding Character. Enable document readers to toggle the display of R code chunks.
#' @param ... Additional arguments of \code{rmarkdown::\link{html_document}()}.
#' 
#' @return An R Markdown output format object
#' @export
#' @examples
#' rmarkdown::render(
#'   input = system.file("rmarkdown", "template.Rmd", package = "finddxtemplate"), 
#'   output_format = html_document_finddx()
#' )
html_document_finddx <- function(toc = TRUE, 
                                 toc_depth = 4, 
                                 toc_float = TRUE, 
                                 code_folding = "show", 
                                 ...) {

  css <- system.file("css", "main.css", package = "finddxtemplate")
  html_template <- system.file("html_template.html", package = "finddxtemplate")

  html_document(
    css = css,
    template = html_template,
    toc = toc,
    toc_depth = toc_depth,
    toc_float = toc_float,
    code_folding = code_folding,
    mathjax = NULL,
    ...
  )
}
